### ISSUE TITLE
The complete dataset Google Drive link is empty

### ISSUE THREAD

**Issue by shivanraptor** [meganndare/cantonese-nlp#6]
Hi there, 

Thanks for the hard work, but I just found out that the complete dataset Google Drive link is empty.
https://drive.google.com/drive/folders/13tWHQkv3MOxVZnz8bMhDOfl6OPSBI6rn?usp=sharing

Can you have a look?

**Comment by meganndare** [comment]
Hi, 

Thank you for bringing this to our attention. The link on the readme should be updated to access the raw data.
